In [1]:
import pandas as pd
import numpy as np
"""
df1=pd.read_csv("SH000300/SH000300_2009_1.csv")
df2=pd.read_csv("SH000300/SH000300_2009_2.csv")
df3=pd.read_csv("SH000300/SH000300_2010_1.csv")
df4=pd.read_csv("SH000300/SH000300_2010_2.csv")
df5=pd.read_csv("SH000300/SH000300_2011_1.csv")
df6=pd.read_csv("SH000300/SH000300_2011_2.csv")
df7=pd.read_csv("SH000300/SH000300_2012_1.csv")
df8=pd.read_csv("SH000300/SH000300_2012_2.csv")
df=pd.concat([df1,df2,df3,df4,df5,df6,df7,df8],axis=0)
"""
df1=pd.read_csv("SH010107/SH010107_2006_2.csv")
df2=pd.read_csv("SH010107/SH010107_2007_1.csv")
df3=pd.read_csv("SH010107/SH010107_2007_2.csv")
df4=pd.read_csv("SH010107/SH010107_2008_1.csv")
df5=pd.read_csv("SH010107/SH010107_2008_2.csv")
df6=pd.read_csv("SH010107/SH010107_2009_1.csv")
df7=pd.read_csv("SH010107/SH010107_2009_2.csv")
df8=pd.read_csv("SH010107/SH010107_2010_1.csv")
df9=pd.read_csv("SH010107/SH010107_2010_2.csv")
df10=pd.read_csv("SH010107/SH010107_2011_1.csv")
df11=pd.read_csv("SH010107/SH010107_2011_2.csv")
df12=pd.read_csv("SH010107/SH010107_2012_1.csv")
df13=pd.read_csv("SH010107/SH010107_2012_2.csv")
df=pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13],axis=0)
df=df.set_index("Date")
print(df)

              Min    Open    High     Low   Close  Adj_Close     Volume
Date                                                                   
2006/7/3     9:31  106.95  106.95  106.95  106.95          5     5348.0
2006/7/3     9:32  106.90  106.90  106.90  106.90         50    53450.0
2006/7/3     9:33  106.90  106.90  106.90  106.90          0        0.0
2006/7/3     9:34  106.90  106.90  106.90  106.90          0        0.0
2006/7/3     9:35  106.90  106.90  106.90  106.90          0        0.0
2006/7/3     9:36  106.90  106.90  106.90  106.90          0        0.0
2006/7/3     9:37  106.90  106.90  106.90  106.90          0        0.0
2006/7/3     9:38  106.90  106.90  106.90  106.90          0        0.0
2006/7/3     9:39  106.90  106.90  106.90  106.90          0        0.0
2006/7/3     9:40  106.90  106.90  106.90  106.90          0        0.0
2006/7/3     9:41  106.89  106.89  106.89  106.89         10    10689.0
2006/7/3     9:42  106.89  106.89  106.89  106.89          0    

In [2]:
#获取日波动率——以DataFrame的格式
returns=df["Close"].pct_change()
volatility=returns.groupby("Date").std()
volatility.name="volatility"
print(volatility)
volatility.head()
lookahead_volatility=volatility.shift(-1).dropna()
#print(lookahead_volatility)#这才是每天对应的下一天的预测值。

Date
2006/10/10    0.000104
2006/10/11    0.000094
2006/10/12    0.000055
2006/10/13    0.000108
2006/10/16    0.000112
2006/10/17    0.000114
2006/10/18    0.000103
2006/10/19    0.000150
2006/10/20    0.000125
2006/10/23    0.000163
2006/10/24    0.000164
2006/10/25    0.000141
2006/10/26    0.000149
2006/10/27    0.000158
2006/10/30    0.000074
2006/10/31    0.000194
2006/10/9     0.000198
2006/11/1     0.000060
2006/11/10    0.000164
2006/11/13    0.000145
2006/11/14    0.000443
2006/11/15    0.000031
2006/11/16    0.000096
2006/11/17    0.000054
2006/11/2     0.000070
2006/11/20    0.000050
2006/11/21    0.000161
2006/11/22    0.000153
2006/11/23    0.000165
2006/11/24    0.000153
                ...   
2012/8/27     0.000176
2012/8/28     0.000160
2012/8/29     0.000293
2012/8/3      0.000163
2012/8/30     0.000195
2012/8/31     0.000123
2012/8/6      0.000235
2012/8/7      0.000208
2012/8/8      0.000162
2012/8/9      0.000245
2012/9/10     0.000127
2012/9/11     0.000087
2012/9

In [3]:
#后面思考这个标准化到底需不需要
norm_data=df[["Open","High","Low","Close"]].apply(lambda x:(x-np.mean(x))/(np.std(x)))
#norm_data=df[["Open","High","Low","Close"]].apply(lambda x:(x-np.min(x))/(np.max(x)-np.min(x)))
#波动率标签先暂时不进行[0,1]
Group_data=norm_data[["Open","High","Low","Close"]].groupby("Date")
#Group_data.apply(lambda x:print(x))
normed_volatility=(lookahead_volatility-np.mean(lookahead_volatility))/(np.std(lookahead_volatility))
#normed_volatility=(lookahead_volatility-np.min(lookahead_volatility))/(np.max(lookahead_volatility)-np.min(lookahead_volatility))
#normed_volatility=lookahead_volatility
print(normed_volatility)

Date
2006/10/10   -0.783924
2006/10/11   -1.054846
2006/10/12   -0.686646
2006/10/13   -0.664823
2006/10/16   -0.645416
2006/10/17   -0.722115
2006/10/18   -0.395568
2006/10/19   -0.574610
2006/10/20   -0.311133
2006/10/23   -0.302966
2006/10/24   -0.464362
2006/10/25   -0.409000
2006/10/26   -0.342987
2006/10/27   -0.924161
2006/10/30   -0.094060
2006/10/31   -0.065479
2006/10/9    -1.023486
2006/11/1    -0.300604
2006/11/10   -0.432549
2006/11/13    1.626375
2006/11/14   -1.221546
2006/11/15   -0.770251
2006/11/16   -1.061503
2006/11/17   -0.949448
2006/11/2    -1.091370
2006/11/20   -0.324546
2006/11/21   -0.376349
2006/11/22   -0.295854
2006/11/23   -0.380000
2006/11/24    0.862628
                ...   
2012/8/24    -0.221484
2012/8/27    -0.327246
2012/8/28     0.593932
2012/8/29    -0.310980
2012/8/3     -0.084534
2012/8/30    -0.585010
2012/8/31     0.188405
2012/8/6      0.002862
2012/8/7     -0.313502
2012/8/8      0.259767
2012/8/9     -0.559241
2012/9/10    -0.836180
2012/9

In [ ]:
def get_train_set(X,Y):
    Xs=[]
    for name, group in X:
        cur_X=group[["Open","High","Low","Close"]].iloc[230:240]
        cur_X_array=np.array(cur_X)
        cur_X_list=cur_X_array.tolist()
        #print(cur_X_list)
        Xs.append(cur_X_list)
    Xs.pop()#将2012/9/7的数据去掉。我们先试图预测一下2012/9/6的波动率。
    return np.array(Xs), np.array(Y)
x,y=get_train_set(Group_data, normed_volatility)
print(x.shape)
print(y.shape)
x_train, x_test=x[:int(len(x) * .9)],x[int(len(x) * .9):-1]
y_train, y_test=y[:int(len(y) * .9)],y[int(len(y) * .9):-1]
#实际上我们得到的数据是今天的价格对应明天的波动率，一直到2012/9/5。事实上这是9-6的输入和输出。
#这里留下最后一行作为预测项。我们希望预测9-7，输入9-6的价格数据，得出9-7的波动率。
x_unknown=x[[-1]]#这是表格上2012/9/6对应的价格数据，实际上是9-7应该的输入，我们估计9-7的波动率。
print(x_unknown.shape)
Y_test=normed_volatility[int(len(x)* .9):]#以DataFrame格式存储以便后面可以调用索引。
print(x_unknown)

(1585, 10, 4)
(1585,)
(1, 10, 4)
[[[0.595407   0.59521703 0.59560509 0.59541197]
  [0.595407   0.59521703 0.59560509 0.59541197]
  [0.595407   0.59521703 0.59560509 0.59541197]
  [0.595407   0.59521703 0.59560509 0.59541197]
  [0.595407   0.59521703 0.59560509 0.59541197]
  [0.595407   0.59521703 0.59560509 0.59541197]
  [0.595407   0.59521703 0.59560509 0.59541197]
  [0.595407   0.59521703 0.59560509 0.59541197]
  [0.595407   0.59521703 0.59560509 0.59541197]
  [0.595407   0.59521703 0.59560509 0.59541197]]]


In [ ]:
from keras.models import Sequential
from keras.models import Model
from keras.layers.core import Dense, Dropout, Activation, Flatten, Permute, RepeatVector
from keras.layers import Merge, Input, concatenate
from keras.layers.recurrent import LSTM, GRU
from keras.layers import Convolution1D, AtrousConvolution1D
from keras.layers.pooling import AveragePooling1D, MaxPooling1D
from keras.callbacks import ModelCheckpoint, ReduceLROnPlateau
from keras.callbacks import CSVLogger
from keras.layers.wrappers import Bidirectional, TimeDistributed
from keras import regularizers
from keras.layers.normalization import BatchNormalization
from keras.layers.advanced_activations import *
from keras.optimizers import RMSprop, Adam, SGD, Nadam
from keras.initializers import *
from keras.constraints import *
from keras import regularizers
from keras import losses

In [ ]:
d= .5
_data_shape = (10, 4)

model = Sequential()


model.add(LSTM(128, input_shape=_data_shape, return_sequences=False))
#model.add(Dropout(d))#d=0.5前面指出了
model.add(Dense(16, kernel_initializer=('uniform'),activation='relu'))
model.add(Dense(1,kernel_initializer='uniform',activation='tanh'))

opt=Nadam(lr=0.02, clipnorm= .1)
reduce_lr=ReduceLROnPlateau(monitor='val_loss', factor=0.9, patience=50, min_lr=0.000001, verbose=1)
#存储模型
checkpointer=ModelCheckpoint(monitor='val_loss',filepath='/Users/tangfuyu/Desktop/code/volatility/model_save1/model_returns.hdf5',verbose=1, save_best_only=True)
#训练模型
model.compile(optimizer=opt, loss='mse')

In [ ]:
_data_shape = (10, 4)
model = Sequential()
model.add(LSTM(128, input_shape=_data_shape, return_sequences=False))
model.add(Dense(16, kernel_initializer=('uniform'),activation='relu'))
model.add(Dense(1,kernel_initializer='uniform',activation='tanh'))
model.compile(optimizer=opt, loss='mse')

In [ ]:
#model_fit是正式开始迭代数据
history=model.fit(
    x_train,#data
    y_train,#labels
    batch_size=60,#是批梯度下降和随机梯度下降的折中方法，将样本数据分为若干批。batch_size是个数。
    epochs=10,#样本中的所有数据被计算一次就是一个epochs
    validation_split=0.1,
    callbacks=[reduce_lr,checkpointer],
    verbose=1)

In [ ]:
#加载模型预测
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
model.load_weights("/Users/tangfuyu/Desktop/experiment/pyexperiment/volatility/model_save1/model_returns.hdf5")
y_pred=model.predict(x_test)
pred_df = pd.DataFrame(np.column_stack([y_test, y_pred]),columns=["y_test","y_pred"])
print(pred_df)
pred_df.plot()
plt.show()

In [ ]:
#在9-7输入9-6的价格数据来获取9-7的波动率。
y_unknown=model.predict(x_unknown)
print(y_unknown)
normed_predict_volatility=y_unknown[0][0]
predict_volatility=normed_predict_volatility*np.std(lookahead_volatility)+np.mean(lookahead_volatility)
print(predict_volatility)
#用2012-9-6的价格序列预测2012-9-7的波动率。实际上是2012-9-6天末到2012-9-7天末的波动率估计。


In [ ]:
#获取每日最高价
high=df["High"].groupby("Date").max()
high.name="High"
print(high.shape)
#获取每日最低价
low=df["Low"].groupby("Date").min()
low.name="Low"
print(low.shape)

In [ ]:
#以词典形式存储对应的开盘价和收盘价再转成dataframe的形式
Open_Dict={}
Close_Dict={}
for name, group in df["Open"].groupby("Date"):
    Open_Dict[name]=group.iloc[0]
for name, group in df["Close"].groupby("Date"):
    Close_Dict[name]=group.iloc[239]
Open=pd.DataFrame.from_dict(Open_Dict, orient='index')
Close=pd.DataFrame.from_dict(Close_Dict, orient='index')
#这里形成的历史数据和前面需要的训练数据不同。这里形成的是每日的价格和对应的波动率。
history_data=pd.concat([Open,high,low,Close,volatility],axis=1).dropna()
history_data.columns=['Open','High','Low','Close','today_volatility']
history=history_data.drop(["2012/9/7"])
print(history)

In [ ]:

#从9-6开始我们已经得到了9月7号的估计波动率。实际上是指从9月6号结束到9月7号结束这一段时间内的波动率。
#取包括2012-9-6往前的500个场景来统计变化。
def get_change(dataframe,future_volatility):#要求参数为dataframe
    Values=[]
    Values_change=[]
    now_value=dataframe.iloc[-1]["Close"]#是9-6的收盘价
    print(now_value)
    for i in range(len(dataframe)-500,len(dataframe),1):#得出500个变化场景。
        after_change=dataframe.iloc[i]["Close"]
        before_change=dataframe.iloc[i-1]["Close"]
        volatility_before=dataframe.iloc[i]["today_volatility"]
        multiple=before_change+(after_change-before_change)*future_volatility/volatility_before
        value=now_value*multiple/before_change
        Values.append(value)
        value_change=value-now_value
        Values_change.append(value_change)
    return Values, Values_change


Values,Values_change=get_change(history,predict_volatility)
print(len(Values))
print(type(Values_change))
        
    
    


    



In [ ]:
#对500个场景进行排序，在1天展望时期以及99%的置信区间下，对应于第5个最糟糕的情形
Values_change.sort()
print(Values_change)
VaR=Values_change[4]
print(VaR)